services:
  - type: web
    name: cedenar-observatorio
    runtime: python
    plan: free
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: cedenar-db
          property: connectionString

databases:
  - name: cedenar-db
    plan: free