# Generated by Django 6.0.2 on 2026-02-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_medidor', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(choices=[('HUAWEI', 'Huawei'), ('GROWATT', 'Growatt')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.CharField(max_length=50)),
                ('medidor', models.CharField(max_length=50)),
                ('fecha_lectura', models.DateTimeField()),
                ('energia_activa_import', models.FloatField()),
                ('energia_reactiva_import', models.FloatField()),
                ('energia_activa_export', models.FloatField()),
                ('energia_reactiva_export', models.FloatField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.proyecto')),
            ],
            options={
                'indexes': [models.Index(fields=['proyecto', 'fecha_lectura'], name='monitoreo_m_proyect_21a287_idx')],
                'unique_together': {('proyecto', 'fecha_lectura')},
            },
        ),
    ]
