# Generated by Django 6.0.2 on 2026-02-19 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el medidor está activo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 19, 13, 24, 3, 911017, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='marca',
            field=models.CharField(blank=True, choices=[('HUAWEI', 'Huawei'), ('GROWATT', 'Growatt')], max_length=20),
        ),
    ]
