# Generated by Django 6.0.2 on 2026-02-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_proyecto_activo_proyecto_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('API_HUAWEI', 'API Huawei'), ('API_GROWATT', 'API Growatt'), ('BASE_DATOS', 'Base de Datos'), ('SERVIDOR', 'Servidor Principal')], max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_verificacion', models.DateTimeField(auto_now=True)),
                ('tiempo_respuesta_ms', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_inactividad', models.BooleanField(default=True, help_text='Enviar alerta si el medidor no envía datos')),
                ('horas_inactividad', models.IntegerField(default=24, help_text='Horas sin datos para considerar inactivo')),
                ('alerta_umbral_generacion', models.BooleanField(default=False, help_text='Enviar alerta si la generación es baja')),
                ('umbral_generacion_kwh', models.FloatField(default=10.0, help_text='Mínimo de generación diaria esperada (kWh)')),
                ('enviar_reporte_semanal', models.BooleanField(default=True, help_text='Enviar reporte semanal por email')),
                ('dia_reporte', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0)),
                ('emails_adicionales', models.TextField(blank=True, help_text='Emails adicionales separados por coma')),
                ('notificaciones_activadas', models.BooleanField(default=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_alerta', to='monitoreo.proyecto')),
            ],
        ),
    ]
