# Generated by Django 6.0.2 on 2026-02-20 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_estadoservidor_configuracionalerta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10)),
                ('layout', models.CharField(choices=[('compacto', 'Compacto'), ('detallado', 'Detallado'), ('tarjetas', 'Tarjetas Grandes')], default='compacto', max_length=20)),
                ('widgets_visibles', models.JSONField(default=list)),
                ('orden_widgets', models.JSONField(default=list)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
