# Generated by Django 6.0.2 on 2026-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_preferenciadashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección física', max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud (ej: 1.227266)', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud (ej: -77.281932)', null=True),
        ),
    ]
