# Generated by Django 6.0.2 on 2026-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_proyecto_direccion_proyecto_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='corriente_ac_a',
            field=models.FloatField(blank=True, help_text='Corriente AC (A)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='corriente_ac_total_a',
            field=models.FloatField(blank=True, help_text='Corriente AC total (A)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='corriente_dc_a',
            field=models.FloatField(blank=True, help_text='Corriente DC (A)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='factor_potencia_pct',
            field=models.FloatField(blank=True, help_text='Factor de potencia (%)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='potencia_aparente_va',
            field=models.FloatField(blank=True, help_text='Potencia aparente (VA)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='potencia_dc_w',
            field=models.FloatField(blank=True, help_text='Potencia DC (W)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='potencia_reactiva_var',
            field=models.FloatField(blank=True, help_text='Potencia reactiva (VAr)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='voltaje_ac_v',
            field=models.FloatField(blank=True, help_text='Voltaje AC (V)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='voltaje_dc_v',
            field=models.FloatField(blank=True, help_text='Voltaje DC (V)', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='voltaje_entre_fases_v',
            field=models.FloatField(blank=True, help_text='Voltaje AC entre fases (V)', null=True),
        ),
    ]
