# Generated by Django 6.0.2 on 2026-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_medicion_corriente_ac_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciadashboard',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciadashboard',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciadashboard',
            name='proyectos_seleccionados',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preferenciadashboard',
            name='tipo_comparacion',
            field=models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes'), ('año', 'Año')], default='mes', max_length=20),
        ),
    ]
