# Generated by Django 6.0.3 on 2026-03-06 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_preferenciadashboard_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('version_politica', models.CharField(default='1.0', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento de datos',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-fecha_aceptacion'],
                'indexes': [models.Index(fields=['usuario', 'version_politica'], name='monitoreo_c_usuario_c2958c_idx')],
            },
        ),
    ]
